# Generated by Django 5.2.4 on 2025-11-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['position'], name='places_imag_positio_b2104b_idx'),
        ),
    ]
