# Generated by Django 5.2.4 on 2025-11-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_place_lat_alter_place_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=20, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=20, verbose_name='Долгота'),
        ),
    ]
